# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'journal_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_journalWindow(object):
    def setupUi(self, journalWindow):
        journalWindow.setObjectName("journalWindow")
        journalWindow.resize(467, 300)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(journalWindow)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonContainer = QtWidgets.QWidget(journalWindow)
        self.buttonContainer.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonContainer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttonContainer.setObjectName("buttonContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttonContainer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.buttonContainer)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.buttonContainer)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.buttonContainer)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.buttonContainer)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(journalWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    border: 0.5px solid black;\n"
"    border-bottom: none;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.lineEdit = QtWidgets.QLineEdit(journalWindow)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 0.5px solid black;\n"
"    border-top: none;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_2 = QtWidgets.QTextEdit(journalWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("QTextEdit {\n"
"    border: 0.5px solid black;\n"
"    border-bottom: none;\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(journalWindow)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 0.5px solid black;\n"
"    border-top: none;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(journalWindow)
        QtCore.QMetaObject.connectSlotsByName(journalWindow)

    def retranslateUi(self, journalWindow):
        _translate = QtCore.QCoreApplication.translate
        journalWindow.setWindowTitle(_translate("journalWindow", "Form"))
        self.pushButton.setText(_translate("journalWindow", "<--"))
        self.pushButton_3.setText(_translate("journalWindow", "Save changes"))
        self.pushButton_2.setText(_translate("journalWindow", "-->"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    journalWindow = QtWidgets.QWidget()
    ui = Ui_journalWindow()
    ui.setupUi(journalWindow)
    journalWindow.show()
    sys.exit(app.exec_())
