# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'journals_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_journalsWindow(object):
    def setupUi(self, journalsWindow):
        journalsWindow.setObjectName("journalsWindow")
        journalsWindow.resize(495, 335)
        self.verticalLayout = QtWidgets.QVBoxLayout(journalsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(journalsWindow)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.journalsContainer = QtWidgets.QWidget(self.widget)
        self.journalsContainer.setObjectName("journalsContainer")
        self.gridLayout = QtWidgets.QGridLayout(self.journalsContainer)
        self.gridLayout.setObjectName("gridLayout")
        self.statusLabel = QtWidgets.QLabel(self.journalsContainer)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.journalsContainer)
        self.buttonsContainer = QtWidgets.QWidget(self.widget)
        self.buttonsContainer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttonsContainer.setObjectName("buttonsContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonsContainer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.importJournal = QtWidgets.QPushButton(self.buttonsContainer)
        self.importJournal.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.importJournal.setFont(font)
        self.importJournal.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"}")
        self.importJournal.setObjectName("importJournal")
        self.horizontalLayout.addWidget(self.importJournal)
        self.viewJournal = QtWidgets.QPushButton(self.buttonsContainer)
        self.viewJournal.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.viewJournal.setFont(font)
        self.viewJournal.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"}")
        self.viewJournal.setObjectName("viewJournal")
        self.horizontalLayout.addWidget(self.viewJournal)
        self.pushButton_3 = QtWidgets.QPushButton(self.buttonsContainer)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.createJournal = QtWidgets.QPushButton(self.buttonsContainer)
        self.createJournal.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createJournal.setFont(font)
        self.createJournal.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"}")
        self.createJournal.setObjectName("createJournal")
        self.horizontalLayout.addWidget(self.createJournal)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.exit = QtWidgets.QPushButton(self.buttonsContainer)
        self.exit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"}")
        self.exit.setObjectName("exit")
        self.horizontalLayout.addWidget(self.exit)
        self.verticalLayout_2.addWidget(self.buttonsContainer)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(journalsWindow)
        QtCore.QMetaObject.connectSlotsByName(journalsWindow)

    def retranslateUi(self, journalsWindow):
        _translate = QtCore.QCoreApplication.translate
        journalsWindow.setWindowTitle(_translate("journalsWindow", "Form"))
        self.importJournal.setText(_translate("journalsWindow", "Import journal"))
        self.viewJournal.setText(_translate("journalsWindow", "View journal"))
        self.pushButton_3.setText(_translate("journalsWindow", "Edit journal"))
        self.createJournal.setText(_translate("journalsWindow", "Create journal"))
        self.exit.setText(_translate("journalsWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    journalsWindow = QtWidgets.QWidget()
    ui = Ui_journalsWindow()
    ui.setupUi(journalsWindow)
    journalsWindow.show()
    sys.exit(app.exec_())
